export { default as board } from './board.png'
export { default as clock } from './clock.png'
export { default as dummyUser } from './dummyUser.png'
export { default as loading } from './loading.gif'
export { default as logoTimeDivider } from './logoTimeDivider.png'
export { default as profile } from './profile.png'
